<?php

namespace TchatBundle\Repository;

/**
 * webchat_linesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class webchat_linesRepository extends \Doctrine\ORM\EntityRepository
{
}
