<?php

namespace TchatBundle\Repository;

/**
 * webchat_usersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class webchat_usersRepository extends \Doctrine\ORM\EntityRepository
{
}
